version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run: apt-get update && apt-get -y install net-tools
      - run: ifconfig
